version: '3'
services:
  x-ui:
    container_name: x-ui
    image: 'x-ui-v3:latest'
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    volumes:
      - '$PWD/db/:/etc/x-ui/'
      - '$PWD/cert/:/root/cert/'
    ports:
      - '54321:54321'
      - '443:443'
      - '80:80'
      - '6061:6061'
    restart: unless-stopped
    tty: true